version: '2'
services:

  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: minesweeper
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: yarn dev

  shell:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: minesweeper
    volumes:
      - .:/usr/src/app
    command: bash
