Description: Creates S3 Bucket with Website hosting configuration

Parameters:
  S3Bucket:
    Type: String
    Description: Name for Website's S3 Bucket
    AllowedPattern: '[a-z0-9-\.]{1,}'

Resources:
  S3BucketWebsite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: S3Bucket
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  S3BucketPolicyPhotoAlbums:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketWebsite
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3BucketWebsite, '/*']]
            Principal: '*'

Outputs:
  WebsiteURL:
    Description: Website URL of created S3 Bucket
    Value: !GetAtt S3BucketWebsite.WebsiteURL
